services:
    Webfactory\NewsletterRegistrationBundle\Form\StartRegistrationType:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\NewsletterRepositoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInFactory'
        tags: ['form.type']

    Webfactory\NewsletterRegistrationBundle\Form\EmailAddressType:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInRepositoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\RecipientRepositoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\EmailAddressFactoryInterface'
        tags: ['form.type']

    Webfactory\NewsletterRegistrationBundle\Entity\EmailAddressFactory:
        arguments:
            - '%secret%'

    Webfactory\NewsletterRegistrationBundle\Entity\EmailAddressFactoryInterface:
        alias: 'Webfactory\NewsletterRegistrationBundle\Entity\EmailAddressFactory'

    Webfactory\NewsletterRegistrationBundle\Form\EditRegistrationType:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\NewsletterRepositoryInterface'
        tags: ['form.type']

    Webfactory\NewsletterRegistrationBundle\Form\DeleteRegistrationType:
        arguments:
            - '@router'
        tags: ['form.type']

    Webfactory\NewsletterRegistrationBundle\Task\StartRegistration:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInRepositoryInterface'
            - '@Symfony\Component\Mailer\MailerInterface'
            - '%webfactory.newsletter_registration.opt_in_sender_address%'
            - '@Twig\Environment'
            - '@Symfony\Component\Routing\RouterInterface'

    Webfactory\NewsletterRegistrationBundle\Task\StartRegistrationInterface:
        alias: 'Webfactory\NewsletterRegistrationBundle\Task\StartRegistration'

    Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInFactory: ~

    Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInFactoryInterface:
        alias: 'Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInFactory'

    Webfactory\NewsletterRegistrationBundle\Task\ConfirmRegistration:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\EmailAddressFactoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\RecipientRepositoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInRepositoryInterface'
            - '@Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface'

    Webfactory\NewsletterRegistrationBundle\Task\ConfirmRegistrationInterface:
        alias: 'Webfactory\NewsletterRegistrationBundle\Task\ConfirmRegistration'

    Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactory: ~

    Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactoryInterface:
        alias: 'Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactory'

    Webfactory\NewsletterRegistrationBundle\Task\EditRegistration:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\RecipientRepositoryInterface'
            - '@Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface'

    Webfactory\NewsletterRegistrationBundle\Task\EditRegistrationInterface:
        alias: 'Webfactory\NewsletterRegistrationBundle\Task\EditRegistration'

    Webfactory\NewsletterRegistrationBundle\Task\DeleteRegistration:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\RecipientRepositoryInterface'
            - '@Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface'

    Webfactory\NewsletterRegistrationBundle\Task\DeleteRegistrationInterface:
        alias: 'Webfactory\NewsletterRegistrationBundle\Task\DeleteRegistration'
