services:
    Webfactory\NewsletterRegistrationBundle\Form\RegisterType:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\NewsletterRepositoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\RecipientRepositoryInterface'
        tags: ['form.type']

    Webfactory\NewsletterRegistrationBundle\Task\SendOptInEmail:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\RecipientRepositoryInterface'
            - '@Symfony\Component\Mailer\MailerInterface'
            - '%webfactory.newsletter_registration.opt_in_sender_address%'
            - '@Twig\Environment'
            - '@Symfony\Component\Routing\RouterInterface'

    Webfactory\NewsletterRegistrationBundle\Task\SendOptInEmailInterface:
        alias: Webfactory\NewsletterRegistrationBundle\Task\SendOptInEmail

    Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactory: ~

    Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactoryInterface:
        alias: 'Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactory'
