services:
    Webfactory\NewsletterRegistrationBundle\Form\RegisterType:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\NewsletterRepositoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInRepositoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\RecipientRepositoryInterface'
            - '%secret%'
        tags: ['form.type']

    Webfactory\NewsletterRegistrationBundle\Task\StartRegistration:
        arguments:
            - '@Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInRepositoryInterface'
            - '@Symfony\Component\Mailer\MailerInterface'
            - '%webfactory.newsletter_registration.opt_in_sender_address%'
            - '@Twig\Environment'
            - '@Symfony\Component\Routing\RouterInterface'

    Webfactory\NewsletterRegistrationBundle\Task\StartRegistrationInterface:
        alias: Webfactory\NewsletterRegistrationBundle\Task\StartRegistration

    Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInFactory:
        arguments:
            - '%secret%'

    Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInFactoryInterface:
        alias: 'Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInFactory'

    Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactory: ~

    Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactoryInterface:
        alias: 'Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactory'

    Webfactory\NewsletterRegistrationBundle\Task\ConfirmRegistration:
        arguments:
            - '%secret%'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\RecipientFactoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\RecipientRepositoryInterface'
            - '@Webfactory\NewsletterRegistrationBundle\Entity\PendingOptInRepositoryInterface'

    Webfactory\NewsletterRegistrationBundle\Task\ConfirmRegistrationInterface:
        alias: Webfactory\NewsletterRegistrationBundle\Task\ConfirmRegistration
