name: Tests

on:
    push:
        branches:
            - master
    pull_request:

env:
    PHP_VERSION: 7.2
    TEMP: ${{ github.workspace }}/tmp

jobs:
    PHPUnit:
        name: PHPUnit
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v3
            -   run: mkdir --mode=777 -p $GITHUB_WORKSPACE/{tmp,logs}
            -   name: Konfiguriere PHP-Version und -Einstellungen im Worker-Node
                uses: shivammathur/setup-php@v2
                with:
                  php-version: ${{ env.PHP_VERSION }}
                  coverage: none
                  tools: composer:v2
                  ini-values: variables_order=EGPCS, date.timezone=Europe/Berlin
            -   name: Cache Composer Dependencies
                uses: actions/cache@v1
                with:
                    path: vendor/
                    key: composer-${{ env.PHP_VERSION }}-${{ hashFiles('composer.*') }}
                    restore-keys: |
                        composer-${{ env.PHP_VERSION }}-${{ github.ref }}
                        composer-${{ env.PHP_VERSION }}-
            -   run: |
                    composer install --no-interaction --no-scripts --no-progress --no-suggest
                    composer show
            -   run: vendor/phpunit/phpunit/phpunit
